# Site settings
title: Magicicada
header-img: img/home-bg.png
email: nicolefederici@yahoo.com
copyright_name: nicolefederici
description: > # this means to ignore newlines until "baseurl:"
  "...the songs of individuals are loud...large choruses can be virtually deafening."
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  nicolefederici
learn_profile: nicolefederici
email_username: nicolefederici@yahoo.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
